import { css } from "styled-system/css";

// Markdown本文の共通スタイル (works / blog / memos)
export const proseStyles = css({
  w: "full",
  lineHeight: "1.75",
  wordBreak: "break-word",
  "& > :first-child": { marginTop: "0 !important" },
  "& h1": {
    fontSize: "2xl",
    fontWeight: "bold",
    mt: "10",
    mb: "5",
    ml: "8",
    lineHeight: "tight",
    position: "relative",
    _before: {
      content: '"##"',
      position: "absolute",
      left: -8,
      top: 0,
      fontSize: "2xl",
      color: "foreground",
    },
  },
  "& h2": {
    fontSize: "xl",
    fontWeight: "semibold",
    mt: "8",
    mb: "4",
    lineHeight: "tight",
  },
  "& h3": {
    fontSize: "lg",
    fontWeight: "semibold",
    mt: "6",
    mb: "3",
    lineHeight: "tight",
  },
  "& h4": {
    fontSize: "md",
    fontWeight: "semibold",
    mt: "5",
    mb: "2",
    lineHeight: "tight",
  },
  "& p": { marginBottom: "1.25rem" },
  "& a": {
    color: "token(colors.primary)",
    textDecoration: "underline",
    fontStyle: "italic",
    _hover: { color: "token(colors.chart3)", textDecorationThickness: "2px" },
  },
  "& ul, & ol": {
    paddingLeft: "1.5rem",
    marginBottom: "1.25rem",
    listStylePosition: "outside",
  },
  "& ul": { listStyleType: "disc" },
  "& ol": { listStyleType: "decimal" },
  "& li": { marginBottom: "0.5rem" },
  "& li::marker": { color: "token(colors.gray.500)" },
  "& blockquote": {
    borderLeft: "4px solid token(colors.primary)",
    padding: "0.75rem 1rem",
    marginBottom: "1.25rem",
    color: "mutedForeground",
    backgroundColor: "muted/50",
    borderRadius: "sm",
    "& > :last-child": { marginBottom: 0 },
  },
  "& pre": {
    backgroundColor: "card",
    color: "cardForeground",
    border: "1px solid token(colors.border)",
    padding: "1rem",
    marginBottom: "1.25rem",
    borderRadius: "md",
    overflowX: "auto",
    fontSize: "sm",
    lineHeight: "1.5",
  },
  "& code": {
    fontFamily: "monospace",
    backgroundColor: "muted",
    color: "primaryForeground",
    padding: "0.15rem 0.3rem",
    borderRadius: "sm",
    fontSize: "0.875em",
    wordBreak: "break-all",
  },
  "& pre code": {
    backgroundColor: "transparent",
    color: "inherit",
    padding: "0",
    fontSize: "inherit",
    fontFamily: "inherit",
  },
  "& hr": {
    borderColor: "border",
    borderTopWidth: "1px",
    marginY: "2rem",
  },
  "& table": {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "sm",
    textAlign: "left",
    marginBottom: "1.25rem",
  },
  "& th, & td": {
    border: "1px solid token(colors.border)",
    padding: "0.5rem 0.75rem",
  },
  "& th": {
    backgroundColor: "muted",
    fontWeight: "semibold",
  },
  "& img": {
    maxWidth: "100%",
    height: "auto",
    borderRadius: "md",
    boxShadow: "sm",
  },
});
